### ISSUE TITLE
Proceed okbuck for project with cutom folder structure

### ISSUE THREAD

**Issue by mr-procrastinator** [OkBuilds/OkBuck#140]
I've project that moved from Eclipse to Android studio, with following sources set:
```
sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }

        // Move the tests to tests/java, tests/res, etc...
        instrumentTest.setRoot('tests')

        // Move the build types to build-types/<type>
        // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...
        // This moves them out of them default location under src/<type>/... which would
        // conflict with src/ being used by the main source set.
        // Adding new build types or product flavors should be accompanied
        // by a similar customization.
        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }
```
There 'res' and 'src' dir placed on same level in MyApp folder. 

During execution of okbuck command, I've faced with following error:

> sub dir res must locate inside resourcesDir dir MyApp

How could I resolve the issue?

**Comment by Piasy** [comment]
please provide stacktrace by adding `--stacktrace`

**Comment by mr-procrastinator** [comment]
```
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.IllegalArgumentException: sub dir res must locate inside resourcesDir dir MyApp
        at com.github.okbuilds.core.util.FileUtil.getRelativePath(FileUtil.groovy:17)
        at com.github.okbuilds.core.util.FileUtil$getRelativePath$1.call(Unknown Source)
        at com.github.okbuilds.core.model.Target$_getAvailable_closure2.doCall(Target.groovy:52)
        at com.github.okbuilds.core.model.Target.getAvailable(Target.groovy:49)
        at com.github.okbuilds.core.model.AndroidTarget$_getResources_closure3.doCall(AndroidTarget.groovy:120)
        at com.github.okbuilds.core.model.AndroidTarget.getResources(AndroidTarget.groovy:119)
        at com.github.okbuilds.core.model.Target.getProperty(Target.groovy)
        at com.github.okbuilds.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:127)
        at com.github.okbuilds.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:180)
        at com.github.okbuilds.okbuck.generator.BuckFileGenerator$_createRules_closure6.doCall(BuckFileGenerator.groovy:68)
        at com.github.okbuilds.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.groovy:59)
        at com.github.okbuilds.okbuck.generator.BuckFileGenerator$_generate_closure2.doCall(BuckFileGenerator.groovy:33)
        at com.github.okbuilds.okbuck.generator.BuckFileGenerator.generate(BuckFileGenerator.groovy:32)
        at com.github.okbuilds.okbuck.generator.BuckFileGenerator$generate.call(Unknown Source)
        at com.github.okbuilds.okbuck.OkBuckGradlePlugin.generate(OkBuckGradlePlugin.groovy:100)
        at com.github.okbuilds.okbuck.OkBuckGradlePlugin$_apply_closure3.doCall(OkBuckGradlePlugin.groovy:59)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
```

**Comment by Piasy** [comment]
So your application module is named as `MyApp`, do you have any resources dir which isn't the child dir of `MyApp`? If so, you need put all your resources dir as child of `MyApp`.

B.T.W. I suggest you use the conventional project structure of AndroidStudio.

**Comment by mr-procrastinator** [comment]
The Point is that the "res" folder are placed inside of "MyApp" directory, but for plugin it is not true. 
Use android studio structure is not the best option because I will lose commit history in that case.

**Comment by kageiit** [comment]
@mr-procrastinator try to create a symlink. It might solve your issue

**Comment by kageiit** [comment]
Feel free to re-open this if the symlink did not solve your issue

**Comment by mr-procrastinator** [comment]
Symlink to res folder?  Also what if I have several targets with old-resource structure, there these targets are placed not in "src" folder.  What should I do that case? Create symlink to nonexisten folder for every target? I am not clear where the library expected to see resources in that case

**Comment by kageiit** [comment]
The folder structure you have is not something buck supports. see 
https://github.com/facebook/buck/blob/b154769ec72f9efebf856779b13cd64d8f54c54a/src/com/facebook/buck/parser/DefaultParserTargetNodeFactory.java#L216

all the source/resource directories of a target need to be inside the same parent directory.
