### ISSUE TITLE
Extra output when running buckw in sample project.

### ISSUE THREAD

**Issue by runningcode** [OkBuilds/OkBuck#168]
I get the following output whenever I run buckw
```
~/Development/OkBuck master * ./buckw
grep: brackets ([ ]) not balanced
usage: git remote add [<options>] <name> <url>

    -f, --fetch           fetch the remote branches
    --tags                import all tags and associated objects when fetching
                          or do not fetch any tag at all (--no-tags)
    -t, --track <branch>  branch(es) to track
    -m, --master <branch>
                          master branch
    --mirror[=<push|fetch>]
                          set up remote as a mirror to push to or fetch from

Traceback (most recent call last):
  File "/Users/no/.gradle/caches/okbuilds/buck/bin/../programs/buck.py", line 9, in <module>
    from buck_tool import BuckToolException, RestartBuck, install_signal_handlers
  File "/Users/no/.gradle/caches/okbuilds/buck/programs/buck_tool.py", line 16, in <module>
    from pynailgun import NailgunConnection, NailgunException
ImportError: No module named pynailgun
```

Let me know if you need any more debugging information.

**Comment by kageiit** [comment]
Interesting. Thanks for the report. Will look into it.

It seems like your buck installation was not clean due to the first message and so you maybe seeing the second message as a result.
